apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework-app.fullname" . }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "homework-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
